### PR TITLE
Hari Hara Sudhan

### PR DESCRIPTION
**Pull request by HariSuriya520**
{
		"name": "Hari Hara Sudhan S",
		"desc": "I'm a 3rd Year Automobile Engineering student with interests in the fields of Networking and Ethical Hacking",
		"github": "https://github.com/HariSuriya520"
	}

### CODE REVIEW

**Comment by r1walz** [comment]
Hey @HariSuriya520 Can you edit the file? And rebase it? You've actually edited the description and that's all. https://github.com/r1walz/git-vcs-workshop/blob/master/script/data.js

**Comment by r1walz** [comment]
Thank you so much or participating!

**Comment by r1walz** [comment]
Thank you so much @HariSuriya520! But you already have your name [published](https://rashiwal.me/git-vcs-workshop/)!

**Comment by HariSuriya520** [comment]
Website link please !
And i didn't receive feedback mail and Certification details !

**Pull request closed without merging**
